In [4]:
import numpy as np

In [11]:
arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [12]:
arr2 = np.array([1,2,3,4,5,6])
arr2.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [17]:
arr3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr3
arr3.shape

(3, 4)

In [23]:
np.arange(0,10,1).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
arr3.ndim

2

In [31]:
arr3.size

12

In [32]:
arr3.dtype

dtype('int64')

In [33]:
arr3.itemsize

8

In [35]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([2,3,4,5,6])

arr1+arr2

array([ 3,  5,  7,  9, 11])

In [37]:
arr1*arr2

array([ 2,  6, 12, 20, 30])

In [38]:
arr1-arr2

array([-1, -1, -1, -1, -1])

In [39]:
arr1/arr2

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333])

In [41]:
arr = np.array([4,5,6,7,8])
np.sqrt(arr)


array([2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712])

In [42]:
np.exp(arr)

array([  54.59815003,  148.4131591 ,  403.42879349, 1096.63315843,
       2980.95798704])

In [43]:
np.sin(arr)

array([-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [44]:
np.log(arr)

array([1.38629436, 1.60943791, 1.79175947, 1.94591015, 2.07944154])

In [45]:
np.log10(arr)

array([0.60205999, 0.69897   , 0.77815125, 0.84509804, 0.90308999])

In [50]:
#slicing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [51]:
arr[1][3]

np.int64(8)

In [57]:
arr[1:2,2:]

array([[7, 8]])

In [58]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [59]:
arr[1:,1:3] = 100
arr

array([[  1,   2,   3,   4],
       [  5, 100, 100,   8],
       [  9, 100, 100,  12]])

In [62]:
data = np.array([2,4,6,8,9])

mean =  np.mean(data)
std_dev = np.std(data)
var = np.var(data)
median = np.median(data)

print(mean,std_dev,var,median)

normalized_data = (data - mean)/std_dev

normalized_data

5.8 2.5612496949731396 6.56 6.0


array([-1.48365074, -0.70278193,  0.07808688,  0.85895569,  1.2493901 ])

In [63]:
data>5

array([False, False,  True,  True,  True])

In [66]:
data = data+1
data

array([ 4,  6,  8, 10, 11])

In [ ]:
data[(data>=5) & (data<=11)]

array([ 6,  8, 10, 11])